require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
$FirebaseSDKVersion = '7.0.0'

target 'cicloo' do
  config = use_native_modules!

  permissions_path = '../node_modules/react-native-permissions/ios'


  use_react_native!(:path => config["reactNativePath"])
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  # pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'
  # pod 'Firebase/Analytics'
  # pod 'Firebase/MLVisionBarcodeModel'
  # pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  #   'BarcodeDetectorMLKit'
  # ]


  
  target 'ciclooTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end
#target 'cicloo-tvOS' do
 # inherit! :search_paths
  # Pods for cicloo-tvOS
#end
#target 'cicloo-tvOSTests' do
  #inherit! :search_paths
  # Pods for testing
#end
